# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kitapekleform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KitapEkleForm(object):
    def setupUi(self, KitapEkleForm):
        KitapEkleForm.setObjectName("KitapEkleForm")
        KitapEkleForm.resize(676, 656)
        self.formLayoutWidget = QtWidgets.QWidget(KitapEkleForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(190, 190, 331, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.kitapAdiLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kitapAdiLabel.setObjectName("kitapAdiLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.kitapAdiLabel)
        self.kitapAdiLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.kitapAdiLineEdit.setObjectName("kitapAdiLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kitapAdiLineEdit)
        self.kitapYazariLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.kitapYazariLabel.setObjectName("kitapYazariLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kitapYazariLabel)
        self.kitapYazariLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.kitapYazariLineEdit.setObjectName("kitapYazariLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kitapYazariLineEdit)
        self.okunmaDurumuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.okunmaDurumuLabel.setObjectName("okunmaDurumuLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.okunmaDurumuLabel)
        self.okunmaDurumuCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.okunmaDurumuCheckBox.setObjectName("okunmaDurumuCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.okunmaDurumuCheckBox)
        self.begeniDurumuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.begeniDurumuLabel.setObjectName("begeniDurumuLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.begeniDurumuLabel)
        self.begeniDurumuLineEdit = QtWidgets.QComboBox(self.formLayoutWidget)
        self.begeniDurumuLineEdit.setObjectName("begeniDurumuLineEdit")
        self.begeniDurumuLineEdit.addItem("")
        self.begeniDurumuLineEdit.addItem("")
        self.begeniDurumuLineEdit.addItem("")
        self.begeniDurumuLineEdit.addItem("")
        self.begeniDurumuLineEdit.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.begeniDurumuLineEdit)
        self.kayitDurumuLabel = QtWidgets.QLabel(KitapEkleForm)
        self.kayitDurumuLabel.setGeometry(QtCore.QRect(280, 310, 101, 16))
        self.kayitDurumuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kayitDurumuLabel.setObjectName("kayitDurumuLabel")
        self.kayitButonu = QtWidgets.QPushButton(KitapEkleForm)
        self.kayitButonu.setGeometry(QtCore.QRect(240, 350, 171, 23))
        self.kayitButonu.setObjectName("kayitButonu")

        self.retranslateUi(KitapEkleForm)
        QtCore.QMetaObject.connectSlotsByName(KitapEkleForm)

    def retranslateUi(self, KitapEkleForm):
        _translate = QtCore.QCoreApplication.translate
        KitapEkleForm.setWindowTitle(_translate("KitapEkleForm", "Form"))
        self.kitapAdiLabel.setText(_translate("KitapEkleForm", "Kitap Adı"))
        self.kitapYazariLabel.setText(_translate("KitapEkleForm", "Kitap Yazarı"))
        self.okunmaDurumuLabel.setText(_translate("KitapEkleForm", "Okunma Durumu"))
        self.begeniDurumuLabel.setText(_translate("KitapEkleForm", "Beğeni Durumu"))
        self.begeniDurumuLineEdit.setItemText(0, _translate("KitapEkleForm", "1"))
        self.begeniDurumuLineEdit.setItemText(1, _translate("KitapEkleForm", "2"))
        self.begeniDurumuLineEdit.setItemText(2, _translate("KitapEkleForm", "3"))
        self.begeniDurumuLineEdit.setItemText(3, _translate("KitapEkleForm", "4"))
        self.begeniDurumuLineEdit.setItemText(4, _translate("KitapEkleForm", "5"))
        self.kayitDurumuLabel.setText(_translate("KitapEkleForm", "Kayıt Durumu"))
        self.kayitButonu.setText(_translate("KitapEkleForm", "Kitap Kaydet"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    KitapEkleForm = QtWidgets.QWidget()
    ui = Ui_KitapEkleForm()
    ui.setupUi(KitapEkleForm)
    KitapEkleForm.show()
    sys.exit(app.exec_())
